server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true

jwt:
  secret: "dnlmbrJGccmaHHe9YYj6+uqCdUO1yycCijMAA70qWlQ="