server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console

jwt:
  secret: "dnlmbrJGccmaHHe9YYj6+uqCdUO1yycCijMAA70qWlQ="